on: [push, pull_request]

name: Rust

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            artifact_name: urban-telegram.exe
            release_name: urban-telegram-windows-amd64.exe
          - os: macos-latest
            artifact_name: urban-telegram
            release_name: urban-telegram-macos-amd64
    steps:
      - uses: actions/checkout@v2
      - name: Remove .cargo/config.toml
        run: rm .cargo/config.toml
      - name: Cache Cargo
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: ${{ matrix.os }}-nightly-cargo-v1
          restore-keys: |
            ${{ matrix.os }}-nightly-cargo-v1
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/install@v1
        with:
          crate: cargo-make
          version: latest
          use-tool-cache: true
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: build-native